web:
  image: embrater_web:latest
  ports:
    - 8000:80
  volumes:
    - ./:/var/www
  links:
    - db
  environment:
    DB_HOST: db
    DB_DATABASE: embrater
    DB_USERNAME: embrater
    DB_PASSWORD: password
    DB_CONNECTION: mysql
db:
  image: mysql
  environment:
    MYSQL_DATABASE: embrater
    MYSQL_USER: root
    MYSQL_PASSWORD: 